### ISSUE TITLE
ClassNotFoundException when deserializing ObjectArray

### ISSUE THREAD

**Issue by dasasian** [sgroschupf/zkclient#33]
Getting the following exception when trying to deserialize an object that contains and array. E.g. Exception.

Caused by: java.lang.ClassNotFoundException: [Ljava.lang.StackTraceElement;
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.I0Itec.zkclient.serialize.TcclAwareObjectInputStream.resolveClass(TcclAwareObjectIputStream.java:44)

This appears to be caused by switching to TcclAwareObjectInputStream from ObjectInputStream in SerializableSerializer.

I was able to fix the issue by changing TcclAwareObjectInputStream resolveClass method.

replace
	return getClass().getClassLoader().loadClass(classDesc.getName());

with
	return super.resolveClass();

**Comment by jzillmann** [comment]
No idea what TcclAwareObjectInputStream is. Its not ZKClient, right ?

**Comment by dasasian** [comment]
Its in this codebase in the serialize package.

org.I0Itec.zkclient.serialize.TcclAwareObjectInputStream

**Comment by jzillmann** [comment]
Ok, i see. Well if we would start using super.resolveClass() the whole class would be ad absurdum i guess. @iocanel you once developed the TcclAwareObjectInputStream. You have some more information about its intent ?

@dasasian workaround would be to implement an own ZkSerializaer and set it on the client, see https://gist.github.com/jjkoshy/3842975

**Comment by iocanel** [comment]
@jzillmann, @dasasian: the TcclAwareObjectInputStream as the name implies is an ObjectInputStream that will fallback to the Thread context classlaoder for loading classes.

A simple object input stream will play nicely when using flat class loader, but will not work at all in environments like OSGi or in some cases when dealing with hierarchical class loaders.

Apparently this doesn't work great for array types.

**Comment by dasasian** [comment]
I did create my own ZkSerializer and set it in the client. But was wondering if there was a solution that handled array types better. Right now it throws that exception at runtime and it was quite hard to track down what the actual issue was, and how to work around it.
